import { PRODUCTS } from './data.js';
import { renderFeatured } from './featured.js';
import { renderMenu } from './menu.js';
import { renderLocations } from './locations.js';
import { updateCartUI, addToCart, changeQty, removeFromCart } from './cart.js';
import { showToast } from './toast.js';
import { goToPage } from './navigation.js';
import { socialsHTML } from './socials.js';
import './search.js';
import './checkout.js';
import './status.js';
import './counter.js';
import './forms.js';
import { triggerReveals } from './reveal.js';
window.addToCart=addToCart; window.changeQty=changeQty; window.removeFromCart=removeFromCart; window.showToast=showToast; window.goToPage=goToPage;
document.getElementById('year').textContent=new Date().getFullYear();
document.getElementById('footerSocials').innerHTML=socialsHTML();
document.getElementById('contactSocials').innerHTML=socialsHTML();
renderFeatured(); renderMenu(); renderLocations(); updateCartUI(); triggerReveals();
